# Generated by Django 5.2 on 2026-03-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_playerrewardclaim_ball_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrewardclaim',
            name='notified',
            field=models.BooleanField(default=False, help_text='Whether the cooldown-ready DM has been sent for the current cycle.'),
        ),
        migrations.AlterField(
            model_name='playerrewardnotification',
            name='enabled',
            field=models.BooleanField(default=False, help_text='If true, bot DMs this player when each reward cooldown expires.'),
        ),
        migrations.AlterField(
            model_name='rewardconfig',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Tick to make this reward command visible and usable in Discord.'),
        ),
        migrations.AlterField(
            model_name='rewardconfig',
            name='max_rarity',
            field=models.FloatField(default=100.0, help_text='Maximum rarity value for eligible collectibles (higher = more common).'),
        ),
        migrations.AlterField(
            model_name='rewardconfig',
            name='min_rarity',
            field=models.FloatField(default=0.0, help_text='Minimum rarity value for eligible collectibles (higher = more common).'),
        ),
        migrations.AlterField(
            model_name='rewardconfig',
            name='reward_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Which reward command this config controls.', max_length=10, unique=True),
        ),
    ]
